defaults: &defaults
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1
  pool: 5
  timeout: 5000

development:
  <<: *defaults
  database: parkrent_development
  username:
  password:

test:
  <<: *defaults
  database: parkrent_test
  username:
  password:
